sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t docker-react .

script:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  regios: "us-west-2"
  app: "docker-react-ankumar"
  env: "DockerReactAnkumar-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-823355659777" 
  bucket_path: "docker-react-ankumar"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
